// cards.seed.js
// Generated seed database for Cardastika.
// Data-check target: 20 collections, 180 collection cards + 9 starter cards = 189 total.
// Starter cards: collectionId === null, isStarter: true — do NOT count toward collection progress.

export const CARD_MAX_LEVEL = 180;

export const ELEMENTS = Object.freeze({
  AIR: 'air',
  WATER: 'water',
  EARTH: 'earth',
  FIRE: 'fire',
});

export const RARITIES = Object.freeze({
  COMMON: 'common',
  UNCOMMON: 'uncommon',
  RARE: 'rare',
  EPIC: 'epic',
  LEGENDARY: 'legendary',
  MYTHIC: 'mythic',
});

export const COLLECTIONS = Object.freeze([
  { id: 'slavic_gods', name: 'Слов’янські боги' },
  { id: 'slavic_spirits', name: 'Слов’янські духи' },
  { id: 'greek_olympians', name: 'Олімпійці' },
  { id: 'greek_creatures', name: 'Грецькі істоти' },
  { id: 'norse_aesir', name: 'Аси' },
  { id: 'norse_creatures', name: 'Скандинавські істоти' },
  { id: 'egyptian_gods', name: 'Єгипетські боги' },
  { id: 'egyptian_spirits', name: 'Єгипетські духи' },
  { id: 'celtic_deities', name: 'Кельтські божества' },
  { id: 'celtic_folklore', name: 'Кельтський фольклор' },
  { id: 'japanese_kami', name: 'Японські камі' },
  { id: 'japanese_yokai', name: 'Японські йокаї' },
  { id: 'hindu_devas', name: 'Індійські деви' },
  { id: 'hindu_epic', name: 'Індійський епос' },
  { id: 'mesopotamian_gods', name: 'Месопотамські боги' },
  { id: 'mesopotamian_creatures', name: 'Месопотамські істоти' },
  { id: 'chinese_deities', name: 'Китайські божества' },
  { id: 'chinese_spirits', name: 'Китайські духи' },
  { id: 'aztec_maya_gods', name: 'Ацтекські та майянські боги' },
  { id: 'world_monsters', name: 'Світові чудовиська' },
]);

export const COLLECTION_CARDS = Object.freeze([
  {
    id: 'slavic_perun',
    name: 'Перун',
    collectionId: 'slavic_gods',
    element: 'air',
    rarity: 'legendary',
    basePower: 51,
    growth: 1.175,
    maxLevel: 180,
    bio: 'Громовержець слов’ян, володар блискавки, неба й воїнської клятви.',
  },
  {
    id: 'slavic_veles',
    name: 'Велес',
    collectionId: 'slavic_gods',
    element: 'earth',
    rarity: 'legendary',
    basePower: 40,
    growth: 1.173,
    maxLevel: 180,
    bio: 'Підземний покровитель худоби, магії, багатства й давніх угод.',
  },
  {
    id: 'slavic_svarog',
    name: 'Сварог',
    collectionId: 'slavic_gods',
    element: 'fire',
    rarity: 'mythic',
    basePower: 124,
    growth: 1.201,
    maxLevel: 180,
    bio: 'Небесний коваль, що викував порядок світу в жарі первісного вогню.',
  },
  {
    id: 'slavic_dazhbog',
    name: 'Дажбог',
    collectionId: 'slavic_gods',
    element: 'fire',
    rarity: 'epic',
    basePower: 22,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Сонячний дарувальник тепла, врожаю й сили для князівських родів.',
  },
  {
    id: 'slavic_mokosh',
    name: 'Мокош',
    collectionId: 'slavic_gods',
    element: 'earth',
    rarity: 'epic',
    basePower: 34,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Мати землі, долі й жіночого ремесла, що тримає нитки життя.',
  },
  {
    id: 'slavic_stribog',
    name: 'Стрибог',
    collectionId: 'slavic_gods',
    element: 'air',
    rarity: 'rare',
    basePower: 19,
    growth: 1.142,
    maxLevel: 180,
    bio: 'Старий володар вітрів, буревіїв і холодних шляхів між небом та полем.',
  },
  {
    id: 'slavic_morana',
    name: 'Морана',
    collectionId: 'slavic_gods',
    element: 'water',
    rarity: 'epic',
    basePower: 30,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Зимова богиня смерті й сну, що веде води під кригою.',
  },
  {
    id: 'slavic_lada',
    name: 'Лада',
    collectionId: 'slavic_gods',
    element: 'water',
    rarity: 'rare',
    basePower: 19,
    growth: 1.138,
    maxLevel: 180,
    bio: 'Покровителька весни, злагоди й тихої сили родинного вогнища.',
  },
  {
    id: 'slavic_yarilo',
    name: 'Ярило',
    collectionId: 'slavic_gods',
    element: 'fire',
    rarity: 'rare',
    basePower: 13,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Весняний вершник пристрасті, сонця й молодої життєвої сили.',
  },
  {
    id: 'slavic_domovyk',
    name: 'Домовик',
    collectionId: 'slavic_spirits',
    element: 'earth',
    rarity: 'common',
    basePower: 3,
    growth: 1.101,
    maxLevel: 180,
    bio: 'Домашній дух, що береже поріг, піч і пам’ять роду.',
  },
  {
    id: 'slavic_lisovyk',
    name: 'Лісовик',
    collectionId: 'slavic_spirits',
    element: 'earth',
    rarity: 'uncommon',
    basePower: 7,
    growth: 1.116,
    maxLevel: 180,
    bio: 'Хитрий господар хащів, який веде чужинців колами між деревами.',
  },
  {
    id: 'slavic_vodyanyk',
    name: 'Водяник',
    collectionId: 'slavic_spirits',
    element: 'water',
    rarity: 'uncommon',
    basePower: 7,
    growth: 1.116,
    maxLevel: 180,
    bio: 'Старий дух ставків і млинів, що затягує необачних у глибину.',
  },
  {
    id: 'slavic_rusalka',
    name: 'Русалка',
    collectionId: 'slavic_spirits',
    element: 'water',
    rarity: 'rare',
    basePower: 12,
    growth: 1.134,
    maxLevel: 180,
    bio: 'Примарна діва води, піснею заманює мандрівників до очеретів.',
  },
  {
    id: 'slavic_polevyk',
    name: 'Польовик',
    collectionId: 'slavic_spirits',
    element: 'earth',
    rarity: 'common',
    basePower: 4,
    growth: 1.107,
    maxLevel: 180,
    bio: 'Дух жнив і межі, що ховається в колоссі під полуденним сонцем.',
  },
  {
    id: 'slavic_bannik',
    name: 'Банник',
    collectionId: 'slavic_spirits',
    element: 'fire',
    rarity: 'common',
    basePower: 1,
    growth: 1.097,
    maxLevel: 180,
    bio: 'Гарячий дух лазні, різкий до тих, хто порушує його порядок.',
  },
  {
    id: 'slavic_baba_yaga',
    name: 'Баба Яга',
    collectionId: 'slavic_spirits',
    element: 'earth',
    rarity: 'epic',
    basePower: 25,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Відьма з межі світу, знає стежки крізь ліс, смерть і випробування.',
  },
  {
    id: 'slavic_zmey_gorynych',
    name: 'Змій Горинич',
    collectionId: 'slavic_spirits',
    element: 'fire',
    rarity: 'legendary',
    basePower: 53,
    growth: 1.173,
    maxLevel: 180,
    bio: 'Багатоголовий змій, що палить пагорби й береже давні скарби.',
  },
  {
    id: 'slavic_kikimora',
    name: 'Кікімора',
    collectionId: 'slavic_spirits',
    element: 'water',
    rarity: 'uncommon',
    basePower: 7,
    growth: 1.122,
    maxLevel: 180,
    bio: 'Тінь у хаті й болоті, що плутає нитки, сни та дрібні людські справи.',
  },
  {
    id: 'greek_zeus',
    name: 'Зевс',
    collectionId: 'greek_olympians',
    element: 'air',
    rarity: 'mythic',
    basePower: 168,
    growth: 1.191,
    maxLevel: 180,
    bio: 'Цар Олімпу, володар грому, закону й небесного суду.',
  },
  {
    id: 'greek_poseidon',
    name: 'Посейдон',
    collectionId: 'greek_olympians',
    element: 'water',
    rarity: 'legendary',
    basePower: 46,
    growth: 1.173,
    maxLevel: 180,
    bio: 'Владика морів, землетрусів і коней, чий тризуб здіймає шторми.',
  },
  {
    id: 'greek_hades',
    name: 'Аїд',
    collectionId: 'greek_olympians',
    element: 'earth',
    rarity: 'legendary',
    basePower: 48,
    growth: 1.175,
    maxLevel: 180,
    bio: 'Мовчазний цар підземного світу, хранитель тіней і скарбів надр.',
  },
  {
    id: 'greek_hera',
    name: 'Гера',
    collectionId: 'greek_olympians',
    element: 'air',
    rarity: 'epic',
    basePower: 22,
    growth: 1.155,
    maxLevel: 180,
    bio: 'Володарка шлюбу й царської гідності, сувора берегиня порядку.',
  },
  {
    id: 'greek_athena',
    name: 'Афіна',
    collectionId: 'greek_olympians',
    element: 'air',
    rarity: 'epic',
    basePower: 21,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Богиня мудрої війни, стратегії, ремесла й холодної перемоги.',
  },
  {
    id: 'greek_apollo',
    name: 'Аполлон',
    collectionId: 'greek_olympians',
    element: 'fire',
    rarity: 'epic',
    basePower: 28,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Сонячний лучник, покровитель пророцтв, музики й очищення.',
  },
  {
    id: 'greek_artemis',
    name: 'Артеміда',
    collectionId: 'greek_olympians',
    element: 'earth',
    rarity: 'rare',
    basePower: 18,
    growth: 1.14,
    maxLevel: 180,
    bio: 'Мисливиця місяця, що береже дикі ліси й непорушну свободу.',
  },
  {
    id: 'greek_ares',
    name: 'Арес',
    collectionId: 'greek_olympians',
    element: 'fire',
    rarity: 'rare',
    basePower: 18,
    growth: 1.13,
    maxLevel: 180,
    bio: 'Бог лютого бою, крові, шаленого натиску й грубої сили.',
  },
  {
    id: 'greek_demeter',
    name: 'Деметра',
    collectionId: 'greek_olympians',
    element: 'earth',
    rarity: 'rare',
    basePower: 13,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Покровителька зерна, родючості й терплячого циклу землі.',
  },
  {
    id: 'greek_satyr',
    name: 'Сатир',
    collectionId: 'greek_creatures',
    element: 'earth',
    rarity: 'common',
    basePower: 1,
    growth: 1.105,
    maxLevel: 180,
    bio: 'Лісовий пустун із козлиними ногами, любить музику, вино й хаос.',
  },
  {
    id: 'greek_harpy',
    name: 'Гарпія',
    collectionId: 'greek_creatures',
    element: 'air',
    rarity: 'uncommon',
    basePower: 9,
    growth: 1.12,
    maxLevel: 180,
    bio: 'Крилата хижачка, що зривається з неба й краде здобич із рук.',
  },
  {
    id: 'greek_centaur',
    name: 'Кентавр',
    collectionId: 'greek_creatures',
    element: 'earth',
    rarity: 'uncommon',
    basePower: 5,
    growth: 1.116,
    maxLevel: 180,
    bio: 'Напівлюдина-напівкінь, швидкий лучник гірських стежок.',
  },
  {
    id: 'greek_minotaur',
    name: 'Мінотавр',
    collectionId: 'greek_creatures',
    element: 'earth',
    rarity: 'rare',
    basePower: 10,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Лабіринтовий биколюд, що нищить ворогів грубою силою рогів.',
  },
  {
    id: 'greek_medusa',
    name: 'Медуза',
    collectionId: 'greek_creatures',
    element: 'earth',
    rarity: 'epic',
    basePower: 20,
    growth: 1.151,
    maxLevel: 180,
    bio: 'Горгона зі зміями замість волосся, її погляд обертає серце в камінь.',
  },
  {
    id: 'greek_cerberus',
    name: 'Цербер',
    collectionId: 'greek_creatures',
    element: 'fire',
    rarity: 'legendary',
    basePower: 40,
    growth: 1.171,
    maxLevel: 180,
    bio: 'Триголовий пес Аїда, сторож брами, звідки не повертаються живі.',
  },
  {
    id: 'greek_hydra',
    name: 'Гідра',
    collectionId: 'greek_creatures',
    element: 'water',
    rarity: 'legendary',
    basePower: 42,
    growth: 1.179,
    maxLevel: 180,
    bio: 'Болотяне чудовисько, що відрощує нові голови замість відрубаних.',
  },
  {
    id: 'greek_pegasus',
    name: 'Пегас',
    collectionId: 'greek_creatures',
    element: 'air',
    rarity: 'rare',
    basePower: 11,
    growth: 1.136,
    maxLevel: 180,
    bio: 'Крилатий кінь, народжений із міфу, швидкий як світанковий вітер.',
  },
  {
    id: 'greek_chimera',
    name: 'Химера',
    collectionId: 'greek_creatures',
    element: 'fire',
    rarity: 'epic',
    basePower: 20,
    growth: 1.145,
    maxLevel: 180,
    bio: 'Змішане чудовисько з левиним ревом, козячою люттю й вогняним подихом.',
  },
  {
    id: 'norse_odin',
    name: 'Одін',
    collectionId: 'norse_aesir',
    element: 'air',
    rarity: 'mythic',
    basePower: 164,
    growth: 1.195,
    maxLevel: 180,
    bio: 'Одноокий Всеотець, шукач рун, битв, мудрості й долі світу.',
  },
  {
    id: 'norse_thor',
    name: 'Тор',
    collectionId: 'norse_aesir',
    element: 'air',
    rarity: 'legendary',
    basePower: 51,
    growth: 1.167,
    maxLevel: 180,
    bio: 'Громовий захисник богів і людей, носій молота Мйольніра.',
  },
  {
    id: 'norse_freyja',
    name: 'Фрейя',
    collectionId: 'norse_aesir',
    element: 'fire',
    rarity: 'legendary',
    basePower: 47,
    growth: 1.165,
    maxLevel: 180,
    bio: 'Пані кохання, війни й сейду, що обирає полеглих героїв.',
  },
  {
    id: 'norse_loki',
    name: 'Локі',
    collectionId: 'norse_aesir',
    element: 'fire',
    rarity: 'epic',
    basePower: 32,
    growth: 1.145,
    maxLevel: 180,
    bio: 'Хитрий мінливець, чия усмішка запускає ланцюг неминучих катастроф.',
  },
  {
    id: 'norse_tyr',
    name: 'Тюр',
    collectionId: 'norse_aesir',
    element: 'earth',
    rarity: 'epic',
    basePower: 27,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Бог честі й договору, що віддав руку заради стримання Фенріра.',
  },
  {
    id: 'norse_baldr',
    name: 'Бальдр',
    collectionId: 'norse_aesir',
    element: 'fire',
    rarity: 'epic',
    basePower: 28,
    growth: 1.159,
    maxLevel: 180,
    bio: 'Світлий бог краси й невинності, чия смерть відкриває шлях Рагнароку.',
  },
  {
    id: 'norse_heimdall',
    name: 'Геймдалль',
    collectionId: 'norse_aesir',
    element: 'air',
    rarity: 'rare',
    basePower: 18,
    growth: 1.14,
    maxLevel: 180,
    bio: 'Сторож райдужного мосту, чує траву й бачить крізь дев’ять світів.',
  },
  {
    id: 'norse_frigg',
    name: 'Фріґґ',
    collectionId: 'norse_aesir',
    element: 'water',
    rarity: 'rare',
    basePower: 13,
    growth: 1.142,
    maxLevel: 180,
    bio: 'Мудра богиня долі й дому, що знає майбутнє, але мовчить.',
  },
  {
    id: 'norse_skadi',
    name: 'Скаді',
    collectionId: 'norse_aesir',
    element: 'water',
    rarity: 'rare',
    basePower: 10,
    growth: 1.14,
    maxLevel: 180,
    bio: 'Льодяна мисливиця гір, що ходить на лижах між бурями й скелями.',
  },
  {
    id: 'norse_dverg',
    name: 'Дверг',
    collectionId: 'norse_creatures',
    element: 'earth',
    rarity: 'common',
    basePower: 3,
    growth: 1.101,
    maxLevel: 180,
    bio: 'Підземний коваль, майстер рунних речей, зброї й хитрих механізмів.',
  },
  {
    id: 'norse_troll',
    name: 'Троль',
    collectionId: 'norse_creatures',
    element: 'earth',
    rarity: 'uncommon',
    basePower: 8,
    growth: 1.122,
    maxLevel: 180,
    bio: 'Грубий мешканець гір, повільний на думку, але страшний у бою.',
  },
  {
    id: 'norse_valkyrie',
    name: 'Валькірія',
    collectionId: 'norse_creatures',
    element: 'air',
    rarity: 'rare',
    basePower: 17,
    growth: 1.142,
    maxLevel: 180,
    bio: 'Крилата діва битви, що несе гідних воїнів до чертогів Одіна.',
  },
  {
    id: 'norse_fenrir',
    name: 'Фенрір',
    collectionId: 'norse_creatures',
    element: 'earth',
    rarity: 'legendary',
    basePower: 52,
    growth: 1.167,
    maxLevel: 180,
    bio: 'Велетенський вовк, закутий богами, але приречений розірвати ланцюги.',
  },
  {
    id: 'norse_jormungandr',
    name: 'Йормунґанд',
    collectionId: 'norse_creatures',
    element: 'water',
    rarity: 'mythic',
    basePower: 82,
    growth: 1.193,
    maxLevel: 180,
    bio: 'Світовий змій, що обвив океани й чекає останнього бою з Тором.',
  },
  {
    id: 'norse_sleipnir',
    name: 'Слейпнір',
    collectionId: 'norse_creatures',
    element: 'air',
    rarity: 'epic',
    basePower: 21,
    growth: 1.147,
    maxLevel: 180,
    bio: 'Восьминогий кінь Одіна, здатний мчати крізь світи живих і мертвих.',
  },
  {
    id: 'norse_nidhogg',
    name: 'Нідгьоґґ',
    collectionId: 'norse_creatures',
    element: 'earth',
    rarity: 'legendary',
    basePower: 42,
    growth: 1.165,
    maxLevel: 180,
    bio: 'Дракон коренів Іґґдрасіля, що гризе основу світового дерева.',
  },
  {
    id: 'norse_fire_giant',
    name: 'Вогняний йотун',
    collectionId: 'norse_creatures',
    element: 'fire',
    rarity: 'epic',
    basePower: 34,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Велетень Муспельгейму, народжений у жарі й попелі кінця світу.',
  },
  {
    id: 'norse_frost_giant',
    name: 'Крижаний йотун',
    collectionId: 'norse_creatures',
    element: 'water',
    rarity: 'rare',
    basePower: 10,
    growth: 1.134,
    maxLevel: 180,
    bio: 'Холодний велетень із краю туманів, сильний у снігу й нічних бурях.',
  },
  {
    id: 'egyptian_ra',
    name: 'Ра',
    collectionId: 'egyptian_gods',
    element: 'fire',
    rarity: 'mythic',
    basePower: 142,
    growth: 1.193,
    maxLevel: 180,
    bio: 'Сонячний творець, що щодня пливе небом і вночі долає пітьму.',
  },
  {
    id: 'egyptian_osiris',
    name: 'Осіріс',
    collectionId: 'egyptian_gods',
    element: 'earth',
    rarity: 'legendary',
    basePower: 35,
    growth: 1.177,
    maxLevel: 180,
    bio: 'Цар мертвих і воскресіння, володар родючої землі після розливу Нілу.',
  },
  {
    id: 'egyptian_isis',
    name: 'Ісіда',
    collectionId: 'egyptian_gods',
    element: 'water',
    rarity: 'legendary',
    basePower: 35,
    growth: 1.173,
    maxLevel: 180,
    bio: 'Велика чарівниця, мати й захисниця, що збирає розірвану долю.',
  },
  {
    id: 'egyptian_set',
    name: 'Сет',
    collectionId: 'egyptian_gods',
    element: 'air',
    rarity: 'epic',
    basePower: 22,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Бог пустелі, бурі й насильства, небезпечний навіть для інших богів.',
  },
  {
    id: 'egyptian_horus',
    name: 'Гор',
    collectionId: 'egyptian_gods',
    element: 'air',
    rarity: 'epic',
    basePower: 26,
    growth: 1.153,
    maxLevel: 180,
    bio: 'Соколиний цар неба, спадкоємець трону й ворог Сета.',
  },
  {
    id: 'egyptian_anubis',
    name: 'Анубіс',
    collectionId: 'egyptian_gods',
    element: 'earth',
    rarity: 'epic',
    basePower: 32,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Шакалоголовий провідник душ, що зважує серце перед вічністю.',
  },
  {
    id: 'egyptian_thoth',
    name: 'Тот',
    collectionId: 'egyptian_gods',
    element: 'air',
    rarity: 'rare',
    basePower: 11,
    growth: 1.134,
    maxLevel: 180,
    bio: 'Писар богів, хранитель міри, мови, знання й священного письма.',
  },
  {
    id: 'egyptian_sekhmet',
    name: 'Сехмет',
    collectionId: 'egyptian_gods',
    element: 'fire',
    rarity: 'rare',
    basePower: 13,
    growth: 1.142,
    maxLevel: 180,
    bio: 'Левиця війни й палючого сонця, що лікує так само люто, як карає.',
  },
  {
    id: 'egyptian_bastet',
    name: 'Бастет',
    collectionId: 'egyptian_gods',
    element: 'earth',
    rarity: 'rare',
    basePower: 13,
    growth: 1.14,
    maxLevel: 180,
    bio: 'Котяча захисниця дому, радості, музики й м’якої нічної сили.',
  },
  {
    id: 'egyptian_ba_bird',
    name: 'Птах Ба',
    collectionId: 'egyptian_spirits',
    element: 'air',
    rarity: 'common',
    basePower: 4,
    growth: 1.099,
    maxLevel: 180,
    bio: 'Крилата частка душі, що вилітає з гробниці й пам’ятає ім’я.',
  },
  {
    id: 'egyptian_ka_guardian',
    name: 'Охоронець Ка',
    collectionId: 'egyptian_spirits',
    element: 'earth',
    rarity: 'uncommon',
    basePower: 7,
    growth: 1.112,
    maxLevel: 180,
    bio: 'Дух життєвої сили, поставлений стерегти тіло й дари померлого.',
  },
  {
    id: 'egyptian_scarab_spirit',
    name: 'Дух скарабея',
    collectionId: 'egyptian_spirits',
    element: 'earth',
    rarity: 'common',
    basePower: 3,
    growth: 1.095,
    maxLevel: 180,
    bio: 'Малий знак відродження, що котить сонце крізь пил і темряву.',
  },
  {
    id: 'egyptian_maat_feather',
    name: 'Перо Маат',
    collectionId: 'egyptian_spirits',
    element: 'air',
    rarity: 'rare',
    basePower: 19,
    growth: 1.132,
    maxLevel: 180,
    bio: 'Священний символ істини, легший за серце праведної душі.',
  },
  {
    id: 'egyptian_ushabti',
    name: 'Ушебті',
    collectionId: 'egyptian_spirits',
    element: 'earth',
    rarity: 'uncommon',
    basePower: 7,
    growth: 1.124,
    maxLevel: 180,
    bio: 'Поховальна статуетка-слуга, що оживає для праці в потойбіччі.',
  },
  {
    id: 'egyptian_sphinx',
    name: 'Сфінкс',
    collectionId: 'egyptian_spirits',
    element: 'earth',
    rarity: 'epic',
    basePower: 26,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Лев із людським лицем, сторож загадок, царської сили й кам’яної тиші.',
  },
  {
    id: 'egyptian_serpopard',
    name: 'Серпопард',
    collectionId: 'egyptian_spirits',
    element: 'fire',
    rarity: 'rare',
    basePower: 16,
    growth: 1.142,
    maxLevel: 180,
    bio: 'Довгошиє чудовисько пустельних меж, символ хаосу старих царств.',
  },
  {
    id: 'egyptian_ammit',
    name: 'Амміт',
    collectionId: 'egyptian_spirits',
    element: 'water',
    rarity: 'legendary',
    basePower: 56,
    growth: 1.181,
    maxLevel: 180,
    bio: 'Пожирачка негідних сердець, суміш крокодила, лева й гіпопотама.',
  },
  {
    id: 'egyptian_akh_spirit',
    name: 'Дух Ах',
    collectionId: 'egyptian_spirits',
    element: 'air',
    rarity: 'epic',
    basePower: 25,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Просвітлена душа, що стала сяйвом і має силу говорити з богами.',
  },
  {
    id: 'celtic_dagda',
    name: 'Дагда',
    collectionId: 'celtic_deities',
    element: 'earth',
    rarity: 'legendary',
    basePower: 55,
    growth: 1.169,
    maxLevel: 180,
    bio: 'Добрий великий бог із палицею, казаном достатку й владою над землею.',
  },
  {
    id: 'celtic_morrigan',
    name: 'Морріґан',
    collectionId: 'celtic_deities',
    element: 'air',
    rarity: 'legendary',
    basePower: 46,
    growth: 1.169,
    maxLevel: 180,
    bio: 'Ворониця війни й долі, що кружляє над полем перед падінням героїв.',
  },
  {
    id: 'celtic_brighid',
    name: 'Бріґід',
    collectionId: 'celtic_deities',
    element: 'fire',
    rarity: 'epic',
    basePower: 32,
    growth: 1.157,
    maxLevel: 180,
    bio: 'Пані вогню, поезії, ремесла й цілющих джерел.',
  },
  {
    id: 'celtic_lugh',
    name: 'Луг',
    collectionId: 'celtic_deities',
    element: 'fire',
    rarity: 'mythic',
    basePower: 126,
    growth: 1.193,
    maxLevel: 180,
    bio: 'Майстер усіх мистецтв, сонячний герой зі списом невідворотної перемоги.',
  },
  {
    id: 'celtic_cernunnos',
    name: 'Кернунн',
    collectionId: 'celtic_deities',
    element: 'earth',
    rarity: 'legendary',
    basePower: 45,
    growth: 1.167,
    maxLevel: 180,
    bio: 'Рогатий володар дикої природи, звірів, коріння й старого лісу.',
  },
  {
    id: 'celtic_manannan',
    name: 'Мананнан',
    collectionId: 'celtic_deities',
    element: 'water',
    rarity: 'epic',
    basePower: 23,
    growth: 1.153,
    maxLevel: 180,
    bio: 'Морський маг у плащі туману, провідник до островів іншого світу.',
  },
  {
    id: 'celtic_danu',
    name: 'Дану',
    collectionId: 'celtic_deities',
    element: 'water',
    rarity: 'rare',
    basePower: 17,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Прадавня мати племені богів, джерело води, крові й спадку.',
  },
  {
    id: 'celtic_nuada',
    name: 'Нуада',
    collectionId: 'celtic_deities',
    element: 'air',
    rarity: 'rare',
    basePower: 14,
    growth: 1.128,
    maxLevel: 180,
    bio: 'Срібнорукий король, що повернув владу через честь і бойову майстерність.',
  },
  {
    id: 'celtic_aengus',
    name: 'Енгус',
    collectionId: 'celtic_deities',
    element: 'water',
    rarity: 'rare',
    basePower: 16,
    growth: 1.134,
    maxLevel: 180,
    bio: 'Юний бог кохання й снів, чиї птахи несуть солодку музику серця.',
  },
  {
    id: 'celtic_leprechaun',
    name: 'Лепрекон',
    collectionId: 'celtic_folklore',
    element: 'earth',
    rarity: 'common',
    basePower: 3,
    growth: 1.099,
    maxLevel: 180,
    bio: 'Малий хитрун-ремісник, що ховає золото там, де закінчується веселка.',
  },
  {
    id: 'celtic_banshee',
    name: 'Банші',
    collectionId: 'celtic_folklore',
    element: 'air',
    rarity: 'rare',
    basePower: 19,
    growth: 1.136,
    maxLevel: 180,
    bio: 'Жінка-плач, чий крик віщує смерть у старих родах.',
  },
  {
    id: 'celtic_pooka',
    name: 'Пука',
    collectionId: 'celtic_folklore',
    element: 'earth',
    rarity: 'uncommon',
    basePower: 6,
    growth: 1.124,
    maxLevel: 180,
    bio: 'Перевертень полів і доріг, що жартує, лякає й веде вершників у ніч.',
  },
  {
    id: 'celtic_kelpie',
    name: 'Келпі',
    collectionId: 'celtic_folklore',
    element: 'water',
    rarity: 'rare',
    basePower: 17,
    growth: 1.142,
    maxLevel: 180,
    bio: 'Водяний кінь, що заманює мандрівників сісти й тягне їх у глибину.',
  },
  {
    id: 'celtic_dullahan',
    name: 'Дуллахан',
    collectionId: 'celtic_folklore',
    element: 'earth',
    rarity: 'epic',
    basePower: 24,
    growth: 1.147,
    maxLevel: 180,
    bio: 'Безголовий вершник, що несе смерть там, де зупиняється його кінь.',
  },
  {
    id: 'celtic_fairy',
    name: 'Фейрі',
    collectionId: 'celtic_folklore',
    element: 'air',
    rarity: 'uncommon',
    basePower: 7,
    growth: 1.124,
    maxLevel: 180,
    bio: 'Небезпечна мала істота пагорбів, красива, примхлива й давня.',
  },
  {
    id: 'celtic_green_man',
    name: 'Зелений чоловік',
    collectionId: 'celtic_folklore',
    element: 'earth',
    rarity: 'epic',
    basePower: 33,
    growth: 1.153,
    maxLevel: 180,
    bio: 'Лице листя й кори, дух весняного відродження та лісового циклу.',
  },
  {
    id: 'celtic_selkie',
    name: 'Селкі',
    collectionId: 'celtic_folklore',
    element: 'water',
    rarity: 'uncommon',
    basePower: 5,
    growth: 1.11,
    maxLevel: 180,
    bio: 'Тюлень-перевертень, що скидає шкіру й виходить на берег людиною.',
  },
  {
    id: 'celtic_redcap',
    name: 'Редкап',
    collectionId: 'celtic_folklore',
    element: 'fire',
    rarity: 'rare',
    basePower: 16,
    growth: 1.14,
    maxLevel: 180,
    bio: 'Кривавий гоблін руїн, що фарбує шапку кров’ю переможених.',
  },
  {
    id: 'japanese_amaterasu',
    name: 'Аматерасу',
    collectionId: 'japanese_kami',
    element: 'fire',
    rarity: 'mythic',
    basePower: 142,
    growth: 1.187,
    maxLevel: 180,
    bio: 'Сонячна богиня, чиє світло повертає світу порядок після темряви.',
  },
  {
    id: 'japanese_susanoo',
    name: 'Сусаноо',
    collectionId: 'japanese_kami',
    element: 'air',
    rarity: 'legendary',
    basePower: 45,
    growth: 1.177,
    maxLevel: 180,
    bio: 'Бурхливий бог штормів, вигнанець і переможець восьмиголового змія.',
  },
  {
    id: 'japanese_tsukuyomi',
    name: 'Цукуйомі',
    collectionId: 'japanese_kami',
    element: 'water',
    rarity: 'legendary',
    basePower: 37,
    growth: 1.169,
    maxLevel: 180,
    bio: 'Місячний камі тиші, нічної рівноваги й холодного світла.',
  },
  {
    id: 'japanese_inari',
    name: 'Інарі',
    collectionId: 'japanese_kami',
    element: 'earth',
    rarity: 'epic',
    basePower: 30,
    growth: 1.151,
    maxLevel: 180,
    bio: 'Камі рису, лисиць, достатку й прихованих шляхів між святинями.',
  },
  {
    id: 'japanese_ryujin',
    name: 'Рюдзін',
    collectionId: 'japanese_kami',
    element: 'water',
    rarity: 'epic',
    basePower: 22,
    growth: 1.147,
    maxLevel: 180,
    bio: 'Драконовий володар моря, що тримає припливи у коштовностях палацу.',
  },
  {
    id: 'japanese_fujin',
    name: 'Фудзін',
    collectionId: 'japanese_kami',
    element: 'air',
    rarity: 'epic',
    basePower: 24,
    growth: 1.151,
    maxLevel: 180,
    bio: 'Демоноподібний камі вітру, несе бурі у великому мішку.',
  },
  {
    id: 'japanese_raijin',
    name: 'Райдзін',
    collectionId: 'japanese_kami',
    element: 'air',
    rarity: 'rare',
    basePower: 11,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Громовий камі з барабанами, чий ритм котиться небом.',
  },
  {
    id: 'japanese_kagutsuchi',
    name: 'Кагуцуті',
    collectionId: 'japanese_kami',
    element: 'fire',
    rarity: 'legendary',
    basePower: 49,
    growth: 1.177,
    maxLevel: 180,
    bio: 'Камі вогню, народження якого принесло біль, смерть і нових богів.',
  },
  {
    id: 'japanese_konohanasakuya',
    name: 'Коноханасакуя',
    collectionId: 'japanese_kami',
    element: 'earth',
    rarity: 'rare',
    basePower: 15,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Принцеса квітів сакури, символ крихкої краси й земного оновлення.',
  },
  {
    id: 'japanese_kappa',
    name: 'Каппа',
    collectionId: 'japanese_yokai',
    element: 'water',
    rarity: 'common',
    basePower: 4,
    growth: 1.103,
    maxLevel: 180,
    bio: 'Водяний йокай із чашею на голові, небезпечний біля річок.',
  },
  {
    id: 'japanese_tengu',
    name: 'Тенґу',
    collectionId: 'japanese_yokai',
    element: 'air',
    rarity: 'rare',
    basePower: 11,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Гірський крилатий воїн, майстер меча, гордості й раптового вітру.',
  },
  {
    id: 'japanese_kitsune',
    name: 'Кіцуне',
    collectionId: 'japanese_yokai',
    element: 'fire',
    rarity: 'epic',
    basePower: 30,
    growth: 1.145,
    maxLevel: 180,
    bio: 'Лисиця-перевертень, що володіє чарами, ілюзіями й вогниками душ.',
  },
  {
    id: 'japanese_oni',
    name: 'Оні',
    collectionId: 'japanese_yokai',
    element: 'fire',
    rarity: 'rare',
    basePower: 10,
    growth: 1.128,
    maxLevel: 180,
    bio: 'Рогатий демон із залізною палицею, грубий, лютий і витривалий.',
  },
  {
    id: 'japanese_yuki_onna',
    name: 'Юкі-онна',
    collectionId: 'japanese_yokai',
    element: 'water',
    rarity: 'epic',
    basePower: 22,
    growth: 1.151,
    maxLevel: 180,
    bio: 'Снігова жінка, що з’являється в заметілі й заморожує подих.',
  },
  {
    id: 'japanese_nurikabe',
    name: 'Нурікабе',
    collectionId: 'japanese_yokai',
    element: 'earth',
    rarity: 'uncommon',
    basePower: 8,
    growth: 1.122,
    maxLevel: 180,
    bio: 'Невидима стіна-йокай, яка перегороджує шлях нічним мандрівникам.',
  },
  {
    id: 'japanese_rokurokubi',
    name: 'Рокурокубі',
    collectionId: 'japanese_yokai',
    element: 'air',
    rarity: 'uncommon',
    basePower: 5,
    growth: 1.11,
    maxLevel: 180,
    bio: 'Йокай із довгою шиєю, що вночі тягнеться крізь темні кімнати.',
  },
  {
    id: 'japanese_umibozu',
    name: 'Умібодзу',
    collectionId: 'japanese_yokai',
    element: 'water',
    rarity: 'legendary',
    basePower: 48,
    growth: 1.165,
    maxLevel: 180,
    bio: 'Морський привид-велетень, що піднімається з хвиль і топить човни.',
  },
  {
    id: 'japanese_tsuchigumo',
    name: 'Цутіґумо',
    collectionId: 'japanese_yokai',
    element: 'earth',
    rarity: 'rare',
    basePower: 10,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Павук-йокай землі, що плете пастки в печерах і забутих домах.',
  },
  {
    id: 'hindu_indra',
    name: 'Індра',
    collectionId: 'hindu_devas',
    element: 'air',
    rarity: 'mythic',
    basePower: 128,
    growth: 1.195,
    maxLevel: 180,
    bio: 'Цар девів, громовержець і переможець змія, що звільнив небесні води.',
  },
  {
    id: 'hindu_agni',
    name: 'Агні',
    collectionId: 'hindu_devas',
    element: 'fire',
    rarity: 'legendary',
    basePower: 56,
    growth: 1.181,
    maxLevel: 180,
    bio: 'Священний вогонь жертвопринесення, посланець між людьми й богами.',
  },
  {
    id: 'hindu_varuna',
    name: 'Варуна',
    collectionId: 'hindu_devas',
    element: 'water',
    rarity: 'legendary',
    basePower: 44,
    growth: 1.177,
    maxLevel: 180,
    bio: 'Володар космічного порядку, вод і невидимих зв’язків клятви.',
  },
  {
    id: 'hindu_vayu',
    name: 'Ваю',
    collectionId: 'hindu_devas',
    element: 'air',
    rarity: 'epic',
    basePower: 24,
    growth: 1.151,
    maxLevel: 180,
    bio: 'Бог вітру й дихання, невидимий рух, що оживляє все живе.',
  },
  {
    id: 'hindu_surya',
    name: 'Сур’я',
    collectionId: 'hindu_devas',
    element: 'fire',
    rarity: 'epic',
    basePower: 30,
    growth: 1.147,
    maxLevel: 180,
    bio: 'Сонячний вершник на колісниці, що бачить усі справи світу.',
  },
  {
    id: 'hindu_yama',
    name: 'Яма',
    collectionId: 'hindu_devas',
    element: 'earth',
    rarity: 'epic',
    basePower: 25,
    growth: 1.155,
    maxLevel: 180,
    bio: 'Суддя померлих і володар межі, де завершується людський шлях.',
  },
  {
    id: 'hindu_lakshmi',
    name: 'Лакшмі',
    collectionId: 'hindu_devas',
    element: 'water',
    rarity: 'rare',
    basePower: 16,
    growth: 1.14,
    maxLevel: 180,
    bio: 'Богиня щастя, краси й достатку, що сходить із вод лотоса.',
  },
  {
    id: 'hindu_saraswati',
    name: 'Сарасваті',
    collectionId: 'hindu_devas',
    element: 'water',
    rarity: 'rare',
    basePower: 16,
    growth: 1.136,
    maxLevel: 180,
    bio: 'Покровителька знання, мови, музики й чистого потоку думки.',
  },
  {
    id: 'hindu_kubera',
    name: 'Кубера',
    collectionId: 'hindu_devas',
    element: 'earth',
    rarity: 'rare',
    basePower: 15,
    growth: 1.142,
    maxLevel: 180,
    bio: 'Хранитель скарбів, володар якшів і важкої сили накопиченого золота.',
  },
  {
    id: 'hindu_vanara_scout',
    name: 'Ванара-розвідник',
    collectionId: 'hindu_epic',
    element: 'earth',
    rarity: 'common',
    basePower: 2,
    growth: 1.095,
    maxLevel: 180,
    bio: 'Мавполюд із загону героїв, швидкий у джунглях і вірний у поході.',
  },
  {
    id: 'hindu_hanuman',
    name: 'Хануман',
    collectionId: 'hindu_epic',
    element: 'air',
    rarity: 'legendary',
    basePower: 35,
    growth: 1.181,
    maxLevel: 180,
    bio: 'Могутній ванара, відданий герой, що стрибає через моря й гори.',
  },
  {
    id: 'hindu_garuda',
    name: 'Ґаруда',
    collectionId: 'hindu_epic',
    element: 'air',
    rarity: 'legendary',
    basePower: 44,
    growth: 1.177,
    maxLevel: 180,
    bio: 'Божественний орел, ворог зміїв і носій небесної швидкості.',
  },
  {
    id: 'hindu_naga',
    name: 'Наґа',
    collectionId: 'hindu_epic',
    element: 'water',
    rarity: 'rare',
    basePower: 18,
    growth: 1.13,
    maxLevel: 180,
    bio: 'Змієподібна істота вод і підземних палаців, мудра й небезпечна.',
  },
  {
    id: 'hindu_rakshasa',
    name: 'Ракшас',
    collectionId: 'hindu_epic',
    element: 'fire',
    rarity: 'rare',
    basePower: 17,
    growth: 1.138,
    maxLevel: 180,
    bio: 'Демонічний воїн ночі, що змінює форму й харчується страхом.',
  },
  {
    id: 'hindu_apsara',
    name: 'Апсара',
    collectionId: 'hindu_epic',
    element: 'water',
    rarity: 'uncommon',
    basePower: 8,
    growth: 1.118,
    maxLevel: 180,
    bio: 'Небесна танцівниця, легка як вода, що зачаровує героїв.',
  },
  {
    id: 'hindu_jatayu',
    name: 'Джатаю',
    collectionId: 'hindu_epic',
    element: 'air',
    rarity: 'epic',
    basePower: 30,
    growth: 1.155,
    maxLevel: 180,
    bio: 'Старий птах-герой, який кинувся проти зла, знаючи ціну бою.',
  },
  {
    id: 'hindu_kumbhakarna',
    name: 'Кумбхакарна',
    collectionId: 'hindu_epic',
    element: 'earth',
    rarity: 'epic',
    basePower: 23,
    growth: 1.145,
    maxLevel: 180,
    bio: 'Велетень зі сном, що триває віки, але пробуджується як катастрофа.',
  },
  {
    id: 'hindu_makara',
    name: 'Макара',
    collectionId: 'hindu_epic',
    element: 'water',
    rarity: 'rare',
    basePower: 12,
    growth: 1.134,
    maxLevel: 180,
    bio: 'Морська істота-вахана, суміш крокодила, риби й міфічної сили.',
  },
  {
    id: 'mesopotamian_marduk',
    name: 'Мардук',
    collectionId: 'mesopotamian_gods',
    element: 'air',
    rarity: 'mythic',
    basePower: 156,
    growth: 1.201,
    maxLevel: 180,
    bio: 'Вавилонський переможець хаосу, що розітнув Тіамат і впорядкував світ.',
  },
  {
    id: 'mesopotamian_ishtar',
    name: 'Іштар',
    collectionId: 'mesopotamian_gods',
    element: 'fire',
    rarity: 'legendary',
    basePower: 49,
    growth: 1.171,
    maxLevel: 180,
    bio: 'Богиня любові й війни, прекрасна, небезпечна й невблаганна.',
  },
  {
    id: 'mesopotamian_enki',
    name: 'Енкі',
    collectionId: 'mesopotamian_gods',
    element: 'water',
    rarity: 'legendary',
    basePower: 46,
    growth: 1.169,
    maxLevel: 180,
    bio: 'Мудрий владика підземних вод, ремесел, магії та людської хитрості.',
  },
  {
    id: 'mesopotamian_enlil',
    name: 'Енліль',
    collectionId: 'mesopotamian_gods',
    element: 'air',
    rarity: 'epic',
    basePower: 20,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Повелитель вітру й царської влади, чий наказ хилить міста.',
  },
  {
    id: 'mesopotamian_utu',
    name: 'Уту',
    collectionId: 'mesopotamian_gods',
    element: 'fire',
    rarity: 'epic',
    basePower: 33,
    growth: 1.145,
    maxLevel: 180,
    bio: 'Сонячний суддя, що бачить правду й освітлює темні справи людей.',
  },
  {
    id: 'mesopotamian_ereskigal',
    name: 'Ерешкігаль',
    collectionId: 'mesopotamian_gods',
    element: 'earth',
    rarity: 'epic',
    basePower: 34,
    growth: 1.147,
    maxLevel: 180,
    bio: 'Цариця підземного царства, непорушна володарка пилу й тіней.',
  },
  {
    id: 'mesopotamian_nanna',
    name: 'Нанна',
    collectionId: 'mesopotamian_gods',
    element: 'water',
    rarity: 'rare',
    basePower: 12,
    growth: 1.134,
    maxLevel: 180,
    bio: 'Місячний бог часу, нічних циклів і срібного світла над містами.',
  },
  {
    id: 'mesopotamian_ninurta',
    name: 'Нінурта',
    collectionId: 'mesopotamian_gods',
    element: 'earth',
    rarity: 'rare',
    basePower: 17,
    growth: 1.132,
    maxLevel: 180,
    bio: 'Воїн і землероб, переможець чудовиськ та охоронець полів.',
  },
  {
    id: 'mesopotamian_tiamat',
    name: 'Тіамат',
    collectionId: 'mesopotamian_gods',
    element: 'water',
    rarity: 'mythic',
    basePower: 152,
    growth: 1.197,
    maxLevel: 180,
    bio: 'Первісна морська безодня, мати чудовиськ і хаос до народження світу.',
  },
  {
    id: 'mesopotamian_lamassu_lesser',
    name: 'Малий Ламассу',
    collectionId: 'mesopotamian_creatures',
    element: 'air',
    rarity: 'common',
    basePower: 4,
    growth: 1.107,
    maxLevel: 180,
    bio: 'Молодий крилатий охоронець брами, ще слабкий, але вже священний.',
  },
  {
    id: 'mesopotamian_lamassu',
    name: 'Ламассу',
    collectionId: 'mesopotamian_creatures',
    element: 'air',
    rarity: 'epic',
    basePower: 21,
    growth: 1.157,
    maxLevel: 180,
    bio: 'Крилатий бик із людським лицем, сторож палаців і царської сили.',
  },
  {
    id: 'mesopotamian_mushussu',
    name: 'Мушхушшу',
    collectionId: 'mesopotamian_creatures',
    element: 'fire',
    rarity: 'legendary',
    basePower: 57,
    growth: 1.171,
    maxLevel: 180,
    bio: 'Дракон Мардука, зміїний звір із лев’ячими лапами й царською люттю.',
  },
  {
    id: 'mesopotamian_utukku',
    name: 'Утукку',
    collectionId: 'mesopotamian_creatures',
    element: 'air',
    rarity: 'rare',
    basePower: 19,
    growth: 1.14,
    maxLevel: 180,
    bio: 'Неспокійний дух пустки, що приносить хвороби, шепіт і холод.',
  },
  {
    id: 'mesopotamian_pazuzu',
    name: 'Пазузу',
    collectionId: 'mesopotamian_creatures',
    element: 'air',
    rarity: 'legendary',
    basePower: 35,
    growth: 1.175,
    maxLevel: 180,
    bio: 'Демон вітрів і сухих бур, страшний захисник від ще гіршого зла.',
  },
  {
    id: 'mesopotamian_gallu',
    name: 'Галлу',
    collectionId: 'mesopotamian_creatures',
    element: 'earth',
    rarity: 'rare',
    basePower: 11,
    growth: 1.144,
    maxLevel: 180,
    bio: 'Підземний демон-переслідувач, що тягне душі до темного суду.',
  },
  {
    id: 'mesopotamian_kusarikku',
    name: 'Кусарікку',
    collectionId: 'mesopotamian_creatures',
    element: 'earth',
    rarity: 'epic',
    basePower: 24,
    growth: 1.161,
    maxLevel: 180,
    bio: 'Биколюд-охоронець, важкий, мов мур, і впертий, мов камінь.',
  },
  {
    id: 'mesopotamian_sirrush',
    name: 'Сірруш',
    collectionId: 'mesopotamian_creatures',
    element: 'fire',
    rarity: 'rare',
    basePower: 12,
    growth: 1.138,
    maxLevel: 180,
    bio: 'Довготілий дракон старих брам, символ сили й царського страху.',
  },
  {
    id: 'mesopotamian_apkallu',
    name: 'Апкаллу',
    collectionId: 'mesopotamian_creatures',
    element: 'water',
    rarity: 'epic',
    basePower: 24,
    growth: 1.155,
    maxLevel: 180,
    bio: 'Напіврибний мудрець, що приніс людям знання, письмо й ритуал.',
  },
  {
    id: 'chinese_jade_emperor',
    name: 'Нефритовий імператор',
    collectionId: 'chinese_deities',
    element: 'air',
    rarity: 'mythic',
    basePower: 94,
    growth: 1.195,
    maxLevel: 180,
    bio: 'Небесний правитель бюрократії богів, порядку й космічної ієрархії.',
  },
  {
    id: 'chinese_guanyin',
    name: 'Ґуаньїнь',
    collectionId: 'chinese_deities',
    element: 'water',
    rarity: 'legendary',
    basePower: 53,
    growth: 1.167,
    maxLevel: 180,
    bio: 'Милосердна заступниця, що чує страждання й несе тиху водну силу.',
  },
  {
    id: 'chinese_nezha',
    name: 'Нечжа',
    collectionId: 'chinese_deities',
    element: 'fire',
    rarity: 'legendary',
    basePower: 49,
    growth: 1.169,
    maxLevel: 180,
    bio: 'Юний войовничий бог із вогняними колесами й непокірним серцем.',
  },
  {
    id: 'chinese_leigong',
    name: 'Лейґун',
    collectionId: 'chinese_deities',
    element: 'air',
    rarity: 'epic',
    basePower: 31,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Громовий володар із молотом, що карає приховану провину.',
  },
  {
    id: 'chinese_longwang',
    name: 'Володар драконів',
    collectionId: 'chinese_deities',
    element: 'water',
    rarity: 'epic',
    basePower: 31,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Цар морських драконів, господар дощів, річок і підводних палаців.',
  },
  {
    id: 'chinese_zhu_rong',
    name: 'Чжу Жун',
    collectionId: 'chinese_deities',
    element: 'fire',
    rarity: 'epic',
    basePower: 31,
    growth: 1.157,
    maxLevel: 180,
    bio: 'Владика вогню, жару й південного небесного порядку.',
  },
  {
    id: 'chinese_houtu',
    name: 'Хоуту',
    collectionId: 'chinese_deities',
    element: 'earth',
    rarity: 'rare',
    basePower: 15,
    growth: 1.13,
    maxLevel: 180,
    bio: 'Земна володарка ґрунту, рівноваги, меж і глибокої стабільності.',
  },
  {
    id: 'chinese_xiwangmu',
    name: 'Сі Ван Му',
    collectionId: 'chinese_deities',
    element: 'earth',
    rarity: 'rare',
    basePower: 10,
    growth: 1.136,
    maxLevel: 180,
    bio: 'Цариця Заходу, хранителька безсмертних персиків і таємних гір.',
  },
  {
    id: 'chinese_chang_e',
    name: 'Чан’е',
    collectionId: 'chinese_deities',
    element: 'water',
    rarity: 'rare',
    basePower: 19,
    growth: 1.136,
    maxLevel: 180,
    bio: 'Місячна богиня самотнього палацу, ніжна й далека як нічне світло.',
  },
  {
    id: 'chinese_huli_jing',
    name: 'Хулі-цзін',
    collectionId: 'chinese_spirits',
    element: 'fire',
    rarity: 'common',
    basePower: 4,
    growth: 1.097,
    maxLevel: 180,
    bio: 'Лисиця-перевертень, що вчиться чарам, спокусі й довгому життю.',
  },
  {
    id: 'chinese_jiangshi',
    name: 'Цзянші',
    collectionId: 'chinese_spirits',
    element: 'earth',
    rarity: 'rare',
    basePower: 15,
    growth: 1.13,
    maxLevel: 180,
    bio: 'Стрибучий мрець, застиглий між смертю, голодом і нічною ци.',
  },
  {
    id: 'chinese_qilin',
    name: 'Цілінь',
    collectionId: 'chinese_spirits',
    element: 'earth',
    rarity: 'legendary',
    basePower: 56,
    growth: 1.179,
    maxLevel: 180,
    bio: 'Священна химерна істота, знак мудрого правління й чистої доброти.',
  },
  {
    id: 'chinese_pixiu',
    name: 'Пісю',
    collectionId: 'chinese_spirits',
    element: 'earth',
    rarity: 'epic',
    basePower: 29,
    growth: 1.145,
    maxLevel: 180,
    bio: 'Крилатий звір багатства, що ковтає скарби й не випускає їх назад.',
  },
  {
    id: 'chinese_ba_she',
    name: 'Ба Ше',
    collectionId: 'chinese_spirits',
    element: 'water',
    rarity: 'rare',
    basePower: 10,
    growth: 1.132,
    maxLevel: 180,
    bio: 'Великий змій, здатний проковтнути слона й чекати роками в болоті.',
  },
  {
    id: 'chinese_fenghuang',
    name: 'Фенхуан',
    collectionId: 'chinese_spirits',
    element: 'fire',
    rarity: 'legendary',
    basePower: 37,
    growth: 1.171,
    maxLevel: 180,
    bio: 'Царський птах гармонії, вогню, чеснот і небесної краси.',
  },
  {
    id: 'chinese_white_tiger',
    name: 'Білий тигр',
    collectionId: 'chinese_spirits',
    element: 'air',
    rarity: 'epic',
    basePower: 34,
    growth: 1.153,
    maxLevel: 180,
    bio: 'Західний небесний звір, хижий символ металу, війни й осені.',
  },
  {
    id: 'chinese_black_tortoise',
    name: 'Чорна черепаха',
    collectionId: 'chinese_spirits',
    element: 'water',
    rarity: 'epic',
    basePower: 33,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Північний звір води й довголіття, черепаха зі змієм у панцирі.',
  },
  {
    id: 'chinese_azure_dragon',
    name: 'Лазуровий дракон',
    collectionId: 'chinese_spirits',
    element: 'air',
    rarity: 'mythic',
    basePower: 114,
    growth: 1.195,
    maxLevel: 180,
    bio: 'Східний небесний дракон весни, грому, росту й імператорської сили.',
  },
  {
    id: 'aztec_quetzalcoatl',
    name: 'Кетцалькоатль',
    collectionId: 'aztec_maya_gods',
    element: 'air',
    rarity: 'mythic',
    basePower: 180,
    growth: 1.191,
    maxLevel: 180,
    bio: 'Пернатий змій вітру, знання й творення, що з’єднує небо та землю.',
  },
  {
    id: 'aztec_huitzilopochtli',
    name: 'Уїцилопочтлі',
    collectionId: 'aztec_maya_gods',
    element: 'fire',
    rarity: 'legendary',
    basePower: 58,
    growth: 1.175,
    maxLevel: 180,
    bio: 'Сонячний бог війни, що веде народ крізь кров, полум’я й перемогу.',
  },
  {
    id: 'aztec_tlaloc',
    name: 'Тлалок',
    collectionId: 'aztec_maya_gods',
    element: 'water',
    rarity: 'legendary',
    basePower: 54,
    growth: 1.169,
    maxLevel: 180,
    bio: 'Володар дощу, грому й родючості, милостивий і страшний одночасно.',
  },
  {
    id: 'aztec_tezcatlipoca',
    name: 'Тескатліпока',
    collectionId: 'aztec_maya_gods',
    element: 'earth',
    rarity: 'legendary',
    basePower: 48,
    growth: 1.167,
    maxLevel: 180,
    bio: 'Димне дзеркало ночі, долі, влади, обману й випробувань.',
  },
  {
    id: 'aztec_xipe_totec',
    name: 'Шіпе-Тотек',
    collectionId: 'aztec_maya_gods',
    element: 'earth',
    rarity: 'epic',
    basePower: 31,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Бог оновлення через жертву, весни, зерна й болісного переродження.',
  },
  {
    id: 'maya_kukulkan',
    name: 'Кукулькан',
    collectionId: 'aztec_maya_gods',
    element: 'air',
    rarity: 'mythic',
    basePower: 118,
    growth: 1.199,
    maxLevel: 180,
    bio: 'Майянський пернатий змій, учитель порядку, зоряних циклів і вітру.',
  },
  {
    id: 'maya_chaac',
    name: 'Чаак',
    collectionId: 'aztec_maya_gods',
    element: 'water',
    rarity: 'epic',
    basePower: 30,
    growth: 1.155,
    maxLevel: 180,
    bio: 'Майянський бог дощу, що розколює небо сокирою блискавки.',
  },
  {
    id: 'maya_itzamna',
    name: 'Іцамна',
    collectionId: 'aztec_maya_gods',
    element: 'air',
    rarity: 'epic',
    basePower: 20,
    growth: 1.149,
    maxLevel: 180,
    bio: 'Старий творець, володар письма, неба, календаря й мудрості.',
  },
  {
    id: 'maya_ixchel',
    name: 'Ішчель',
    collectionId: 'aztec_maya_gods',
    element: 'water',
    rarity: 'rare',
    basePower: 16,
    growth: 1.13,
    maxLevel: 180,
    bio: 'Місячна богиня води, ткацтва, лікування й жіночих циклів.',
  },
  {
    id: 'world_dragon',
    name: 'Дракон',
    collectionId: 'world_monsters',
    element: 'fire',
    rarity: 'legendary',
    basePower: 42,
    growth: 1.173,
    maxLevel: 180,
    bio: 'Стародавній крилатий звір, що збирає золото й випалює королівства.',
  },
  {
    id: 'world_phoenix',
    name: 'Фенікс',
    collectionId: 'world_monsters',
    element: 'fire',
    rarity: 'mythic',
    basePower: 139,
    growth: 1.195,
    maxLevel: 180,
    bio: 'Птах вічного вогню, що згорає й народжується з власного попелу.',
  },
  {
    id: 'world_leviathan',
    name: 'Левіафан',
    collectionId: 'world_monsters',
    element: 'water',
    rarity: 'mythic',
    basePower: 90,
    growth: 1.189,
    maxLevel: 180,
    bio: 'Морська безодня у формі чудовиська, здатна ковтати флоти.',
  },
  {
    id: 'world_behemoth',
    name: 'Бегемот',
    collectionId: 'world_monsters',
    element: 'earth',
    rarity: 'mythic',
    basePower: 99,
    growth: 1.197,
    maxLevel: 180,
    bio: 'Наземний титан первісної сили, важчий за гори й старший за царства.',
  },
  {
    id: 'world_griffin',
    name: 'Грифон',
    collectionId: 'world_monsters',
    element: 'air',
    rarity: 'epic',
    basePower: 28,
    growth: 1.151,
    maxLevel: 180,
    bio: 'Орел-лев, сторож скарбів і високих перевалів, гордий та пильний.',
  },
  {
    id: 'world_basilisk',
    name: 'Василіск',
    collectionId: 'world_monsters',
    element: 'earth',
    rarity: 'epic',
    basePower: 32,
    growth: 1.159,
    maxLevel: 180,
    bio: 'Отруйний цар зміїв, чий погляд несе смерть і кам’яну тишу.',
  },
  {
    id: 'world_manticore',
    name: 'Мантикора',
    collectionId: 'world_monsters',
    element: 'fire',
    rarity: 'epic',
    basePower: 24,
    growth: 1.155,
    maxLevel: 180,
    bio: 'Левине чудовисько з жалом, людським лицем і голодом до битви.',
  },
  {
    id: 'world_roc',
    name: 'Рух',
    collectionId: 'world_monsters',
    element: 'air',
    rarity: 'legendary',
    basePower: 56,
    growth: 1.165,
    maxLevel: 180,
    bio: 'Гігантський птах, що підіймає слонів і ховає сонце крилами.',
  },
  {
    id: 'world_kraken',
    name: 'Кракен',
    collectionId: 'world_monsters',
    element: 'water',
    rarity: 'legendary',
    basePower: 43,
    growth: 1.167,
    maxLevel: 180,
    bio: 'Щупальцевий жах глибин, що розламує кораблі під чорними хвилями.',
  },
]);

export const STARTER_CARDS = Object.freeze([
  {
    id: 'starter_wind_squire',
    name: 'Вітряний зброєносець',
    collectionId: null,
    element: 'air',
    rarity: 'common',
    basePower: 3,
    growth: 1.095,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Молодий боєць із легким клинком, що вчиться читати рух вітру.',
  },
  {
    id: 'starter_river_apprentice',
    name: 'Учень річки',
    collectionId: null,
    element: 'water',
    rarity: 'common',
    basePower: 3,
    growth: 1.095,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Спокійний новачок, що тримає оборону плавно, мов течія.',
  },
  {
    id: 'starter_ember_guard',
    name: 'Жевріючий вартовий',
    collectionId: null,
    element: 'fire',
    rarity: 'common',
    basePower: 4,
    growth: 1.098,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Початковий воїн жару, сміливий у першому ударі, але ще нестійкий.',
  },
  {
    id: 'starter_root_keeper',
    name: 'Кореневий сторож',
    collectionId: null,
    element: 'earth',
    rarity: 'common',
    basePower: 4,
    growth: 1.098,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Міцний захисник із дерев’яним щитом, народжений для довгого бою.',
  },
  {
    id: 'starter_cloud_archer',
    name: 'Хмарний лучник',
    collectionId: null,
    element: 'air',
    rarity: 'common',
    basePower: 2,
    growth: 1.092,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Легкий стрілець, що б’є здалеку й відступає швидше за подих.',
  },
  {
    id: 'starter_brook_healer',
    name: 'Джерельна цілителька',
    collectionId: null,
    element: 'water',
    rarity: 'common',
    basePower: 2,
    growth: 1.092,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Тиха берегиня джерела, слабка в атаці, але витривала духом.',
  },
  {
    id: 'starter_ash_blade',
    name: 'Попільний клинок',
    collectionId: null,
    element: 'fire',
    rarity: 'common',
    basePower: 3,
    growth: 1.095,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Юний мечник, що носить клинок із темним слідом згаслого полум’я.',
  },
  {
    id: 'starter_stone_pawn',
    name: 'Кам’яний ратник',
    collectionId: null,
    element: 'earth',
    rarity: 'common',
    basePower: 3,
    growth: 1.095,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Простий боєць першої лінії, повільний, але надійний як камінь.',
  },
  {
    id: 'starter_mist_wanderer',
    name: 'Мандрівник туману',
    collectionId: null,
    element: 'water',
    rarity: 'common',
    basePower: 4,
    growth: 1.098,
    maxLevel: 180,
    isStarter: true,
    isCollectionCard: false,
    bio: 'Невідомий подорожній, що з’являється з туману на початку шляху.',
  },
]);

export const CARDS = Object.freeze([...STARTER_CARDS, ...COLLECTION_CARDS]);

export function validateCardsSeed(cards = CARDS, collections = COLLECTIONS) {
  const collectionCards = cards.filter(card => card.collectionId !== null);
  const collectionIds = new Set(collections.map(collection => collection.id));
  const ids = cards.map(card => card.id);
  const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);

  const byCollection = collectionCards.reduce((acc, card) => {
    acc[card.collectionId] = (acc[card.collectionId] || 0) + 1;
    return acc;
  }, {});

  const invalidCollectionCounts = Object.entries(byCollection)
    .filter(([, count]) => count !== 9)
    .map(([collectionId, count]) => ({ collectionId, count }));

  const unknownCollections = collectionCards
    .filter(card => !collectionIds.has(card.collectionId))
    .map(card => card.collectionId);

  const tooLongBio = cards
    .filter(card => card.bio.length > 140)
    .map(card => ({ id: card.id, length: card.bio.length }));

  const starterCards = cards.filter(card => card.isStarter === true);

  return {
    collectionsCount: collections.length,
    collectionCardsCount: collectionCards.length,
    starterCardsCount: starterCards.length,
    totalCardsCount: cards.length,
    uniqueCardIds: new Set(ids).size,
    duplicateIds: [...new Set(duplicateIds)],
    invalidCollectionCounts,
    unknownCollections: [...new Set(unknownCollections)],
    tooLongBio,
    ok:
      collections.length === 20 &&
      collectionCards.length === 180 &&
      starterCards.length === 9 &&
      new Set(ids).size === cards.length &&
      invalidCollectionCounts.length === 0 &&
      unknownCollections.length === 0 &&
      tooLongBio.length === 0,
  };
}

export const CARDS_SEED_CHECK = validateCardsSeed();
