import { cards } from '../data/cards.js';
import { collections } from '../data/collections.js';

export const initialState = {
  player: {
    name: 'Гравець',
    level: 34,
    power: 108,
    exp: 0,
    expToNext: 100,
    // Встановлено тимчасово для тесту
    gold: 5000,
    silver: 0,
    gems: 0,
    stars: 0,
  },
  modes: [
    { id: 'duel', title: 'Дуелі', stat: '', icon: 'swords', iconColor: '#f2c94c', gradient: 'duel' },
    { id: 'campaign', title: 'Кампанія', stat: '', icon: 'campaign', iconColor: '#00d2ff', gradient: 'camp' },
    { id: 'tournament', title: 'Турнір', stat: '', icon: 'tournament', iconColor: '#a0a0a0', gradient: 'tour' },
    { id: 'arena', title: 'Арена', stat: '', icon: 'arena', iconColor: '#a0a0a0', gradient: 'arena' },
    { id: 'deck', title: 'Колода', stat: '', icon: 'deck', iconColor: '#2ecc71', gradient: 'deck' },
    { id: 'invasion', title: 'Нашестя', stat: '', icon: 'invasion', iconColor: '#ff4500', gradient: 'invasion' },
  ],
  listItems: [
    { id: 'tasks', title: 'Завдання', icon: 'tasks', iconColor: '#00ff00', hasDot: false },
    { id: 'diamonds', title: 'Алмазні нагороди', icon: 'diamonds', iconColor: '#00d2ff', hasDot: false },
    { id: 'equipment', title: 'Спорядження', icon: 'equipment', iconColor: '#b7b1a2', hasDot: false },
    { id: 'collections', title: 'Колекції', icon: 'collections', iconColor: '#f2c94c', hasDot: false },
    { id: 'best', title: 'Кращі', icon: 'best', iconColor: '#ffd700', hasDot: false },
    { id: 'shop', title: 'Магазин', icon: 'shop', iconColor: '#cccccc', hasDot: false },
  ],
  tasks: { hasNew: false, count: 0 },
  goldTimer: { hours: 4, minutes: 16 },
  cards,
  collections,
  ownedCardIds: [
    // 9 стартових карт — без колекції, формують першу бойову колоду
    'starter_wind_squire',
    'starter_river_apprentice',
    'starter_ember_guard',
    'starter_root_keeper',
    'starter_cloud_archer',
    'starter_brook_healer',
    'starter_ash_blade',
    'starter_stone_pawn',
    'starter_mist_wanderer',
  ],
  selectedCollectionId: null,
  selectedCardId: null,
  starterCards: [
    {
      id: 1,
      name: 'Лісовик',
      origin: 'Слов’янський фольклор',
      element: 'earth',
      elementName: 'Земля',
      power: 4,
      note: 'базовий захисник',
    },
    {
      id: 2,
      name: 'Домовик',
      origin: 'Слов’янський фольклор',
      element: 'earth',
      elementName: 'Земля',
      power: null,
      note: 'слабка, але атмосферна стартова карта',
    },
    {
      id: 3,
      name: 'Русалка',
      origin: 'Слов’янський фольклор',
      element: 'water',
      elementName: 'Вода',
      power: null,
      note: 'стартова водна карта',
    },
    {
      id: 4,
      name: 'Воїн Перуна',
      origin: 'Слов’янський пантеон',
      element: 'air',
      elementName: 'Повітря',
      power: null,
      note: 'не сам Перун, а його воїн',
    },
    {
      id: 5,
      name: 'Жрець Велеса',
      origin: 'Слов’янський пантеон',
      element: 'earth',
      elementName: 'Земля',
      power: null,
      note: 'містична земляна карта',
    },
    {
      id: 6,
      name: 'Саламандра',
      origin: 'Європейський фольклор',
      element: 'fire',
      elementName: 'Вогонь',
      power: null,
      note: 'базовий вогняний звір',
    },
    {
      id: 7,
      name: 'Водяний слуга',
      origin: 'Слов’янський фольклор',
      element: 'water',
      elementName: 'Вода',
      power: null,
      note: 'проста водна істота',
    },
    {
      id: 8,
      name: 'Вітряний дух',
      origin: 'Балто-слов’янський фольклор',
      element: 'air',
      elementName: 'Повітря',
      power: null,
      note: 'базова карта повітря',
    },
    {
      id: 9,
      name: 'Іскровик',
      origin: 'Народна міфологія / авторська фольклорна істота',
      element: 'fire',
      elementName: 'Вогонь',
      power: 3,
      note: 'слабка вогняна карта',
    },
  ],
  activeTab: 'deck',
};
