export const QUALITY_LEVEL_RANGES = {
  common: [1, 4],
  uncommon: [5, 9],
  rare: [10, 19],
  epic: [20, 34],
  legendary: [35, 59],
  mythic: [60, 180],
};

export const SILVER_500_CARD_POOL = [
  'slavic_domovyk',
  'slavic_lisovyk',
  'slavic_vodyanyk',
  'slavic_rusalka',
  'slavic_polevyk',
  'slavic_bannik',
  'slavic_baba_yaga',
  'slavic_zmey_gorynych',
  'slavic_kikimora',
  'greek_satyr',
  'greek_harpy',
  'greek_centaur',
  'greek_minotaur',
  'greek_medusa',
  'greek_cerberus',
  'greek_hydra',
  'greek_pegasus',
  'greek_chimera',
  'norse_dverg',
  'norse_troll',
  'norse_valkyrie',
  'norse_fenrir',
  'norse_jormungandr',
  'norse_sleipnir',
  'norse_nidhogg',
  'norse_fire_giant',
  'norse_frost_giant',
  'egyptian_ba_bird',
  'egyptian_ka_guardian',
  'egyptian_scarab_spirit',
  'egyptian_maat_feather',
  'egyptian_ushabti',
  'egyptian_sphinx',
  'egyptian_serpopard',
  'egyptian_ammit',
  'egyptian_akh_spirit',
  'celtic_leprechaun',
  'celtic_banshee',
  'celtic_pooka',
  'celtic_kelpie',
  'celtic_dullahan',
  'celtic_fairy',
  'celtic_green_man',
  'celtic_selkie',
  'celtic_redcap',
  'japanese_kappa',
  'japanese_tengu',
  'japanese_kitsune',
  'japanese_oni',
  'japanese_yuki_onna',
  'japanese_nurikabe',
  'japanese_rokurokubi',
  'japanese_umibozu',
  'japanese_tsuchigumo',
  'hindu_vanara_scout',
  'hindu_hanuman',
  'hindu_garuda',
  'hindu_naga',
  'hindu_rakshasa',
  'hindu_apsara',
  'hindu_jatayu',
  'hindu_kumbhakarna',
  'hindu_makara',
  'mesopotamian_lamassu_lesser',
  'mesopotamian_lamassu',
  'mesopotamian_mushussu',
  'mesopotamian_utukku',
  'mesopotamian_pazuzu',
  'mesopotamian_gallu',
  'mesopotamian_kusarikku',
  'mesopotamian_sirrush',
  'mesopotamian_apkallu',
  'chinese_huli_jing',
  'chinese_jiangshi',
  'chinese_qilin',
  'chinese_pixiu',
  'chinese_ba_she',
  'chinese_fenghuang',
  'chinese_white_tiger',
  'chinese_black_tortoise',
  'chinese_azure_dragon',
  'world_dragon',
  'world_phoenix',
  'world_leviathan',
  'world_behemoth',
  'world_griffin',
  'world_basilisk',
  'world_manticore',
  'world_roc',
  'world_kraken',
];

export const GOLD_50_CARD_POOL = [
  'slavic_perun',
  'slavic_veles',
  'slavic_svarog',
  'slavic_dazhbog',
  'slavic_mokosh',
  'slavic_stribog',
  'slavic_morana',
  'slavic_lada',
  'slavic_yarilo',
  'greek_zeus',
  'greek_poseidon',
  'greek_hades',
  'greek_hera',
  'greek_athena',
  'greek_apollo',
  'greek_artemis',
  'greek_ares',
  'greek_demeter',
  'norse_odin',
  'norse_thor',
  'norse_freyja',
  'norse_loki',
  'norse_tyr',
  'norse_baldr',
  'norse_heimdall',
  'norse_frigg',
  'norse_skadi',
  'egyptian_ra',
  'egyptian_osiris',
  'egyptian_isis',
  'egyptian_set',
  'egyptian_horus',
  'egyptian_anubis',
  'egyptian_thoth',
  'egyptian_sekhmet',
  'egyptian_bastet',
  'celtic_dagda',
  'celtic_morrigan',
  'celtic_brighid',
  'celtic_lugh',
  'celtic_cernunnos',
  'celtic_manannan',
  'celtic_danu',
  'celtic_nuada',
  'celtic_aengus',
  'japanese_amaterasu',
  'japanese_susanoo',
  'japanese_tsukuyomi',
  'japanese_inari',
  'japanese_ryujin',
  'japanese_fujin',
  'japanese_raijin',
  'japanese_kagutsuchi',
  'japanese_konohanasakuya',
  'hindu_indra',
  'hindu_agni',
  'hindu_varuna',
  'hindu_vayu',
  'hindu_surya',
  'hindu_yama',
  'hindu_lakshmi',
  'hindu_saraswati',
  'hindu_kubera',
  'mesopotamian_marduk',
  'mesopotamian_ishtar',
  'mesopotamian_enki',
  'mesopotamian_enlil',
  'mesopotamian_utu',
  'mesopotamian_ereskigal',
  'mesopotamian_nanna',
  'mesopotamian_ninurta',
  'mesopotamian_tiamat',
  'chinese_jade_emperor',
  'chinese_guanyin',
  'chinese_nezha',
  'chinese_leigong',
  'chinese_longwang',
  'chinese_zhu_rong',
  'chinese_houtu',
  'chinese_xiwangmu',
  'chinese_chang_e',
  'aztec_quetzalcoatl',
  'aztec_huitzilopochtli',
  'aztec_tlaloc',
  'aztec_tezcatlipoca',
  'aztec_xipe_totec',
  'maya_kukulkan',
  'maya_chaac',
  'maya_itzamna',
  'maya_ixchel',
];

export const GOLD_150_CARD_POOL = [
  'slavic_perun',
  'slavic_veles',
  'slavic_svarog',
  'greek_zeus',
  'greek_poseidon',
  'greek_hades',
  'norse_odin',
  'norse_thor',
  'norse_freyja',
  'egyptian_ra',
  'egyptian_osiris',
  'egyptian_isis',
  'celtic_dagda',
  'celtic_morrigan',
  'celtic_brighid',
  'japanese_amaterasu',
  'japanese_susanoo',
  'japanese_tsukuyomi',
  'hindu_indra',
  'hindu_agni',
  'hindu_varuna',
  'mesopotamian_marduk',
  'mesopotamian_ishtar',
  'mesopotamian_enki',
  'chinese_jade_emperor',
  'chinese_guanyin',
  'chinese_nezha',
  'aztec_quetzalcoatl',
  'aztec_huitzilopochtli',
  'aztec_tlaloc',
];

export const HIGH_MAGES_SPECIAL_EXISTING_POOL = [
  'slavic_svarog',
  'greek_hades',
  'norse_odin',
  'egyptian_thoth',
  'celtic_dagda',
  'japanese_tsukuyomi',
  'hindu_varuna',
  'mesopotamian_enki',
  'chinese_nezha',
];

export const SHOP_CARD_PACKS = {
  silver_500: {
    id: 'silver_500',
    title: 'Незвичайна карта',
    subtitle: 'Гарантована незвичайна карта з шансом рідкісної або епічної.',
    type: 'shop-card-pack',
    price: { currency: 'silver', amount: 500 },
    guaranteedQuality: 'uncommon',
    higherQualities: ['rare', 'epic'],
    startChance: { rare: 5, epic: 1 },
    failIncrement: { rare: 1, epic: 0.25 },
    cardPool: SILVER_500_CARD_POOL,
    color: 'green',
    chanceRarity: 'epic',
  },
  gold_50: {
    id: 'gold_50',
    title: 'Епічна карта',
    subtitle: 'Гарантована епічна карта з шансом легендарної або міфічної.',
    type: 'shop-card-pack',
    price: { currency: 'gold', amount: 50 },
    altPrice: { currency: 'gems', amount: 100 },
    guaranteedQuality: 'epic',
    higherQualities: ['legendary', 'mythic'],
    startChance: { legendary: 5, mythic: 1 },
    failIncrement: { legendary: 1, mythic: 0.25 },
    titleModifiers: {
      absolute_champion: {
        failIncrement: { mythic: 1 },
      },
    },
    cardPool: GOLD_50_CARD_POOL,
    color: 'purple',
    chanceRarity: 'mythic',
  },
  gold_150: {
    id: 'gold_150',
    title: 'Легендарна карта',
    subtitle: 'Гарантована легендарна карта з шансом міфічної.',
    type: 'shop-card-pack',
    price: { currency: 'gold', amount: 150 },
    altPrice: { currency: 'gems', amount: 300 },
    guaranteedQuality: 'legendary',
    higherQualities: ['mythic'],
    startChance: { mythic: 5 },
    failIncrement: { mythic: 1 },
    specialDrop: {
      id: 'higher_mages',
      name: 'Вищі маги',
      requiredPlayerLevel: 75,
      requiredPower: 6400,
      extraMythicChance: 3,
      cardPool: HIGH_MAGES_SPECIAL_EXISTING_POOL,
    },
    cardPool: GOLD_150_CARD_POOL,
    color: 'orange',
    chanceRarity: 'mythic',
  },
};

export const CARD_PACKS = Object.values(SHOP_CARD_PACKS);
